import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { Inter, Roboto } from 'next/font/google';
import NavLink from '../../components/NavLink';


const inter=Inter({subsets:["latin"]});

const roboto=Roboto({weight:"400", subsets:["latin"]});



export const metadata: Metadata = {
  title: "Karthik's Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-white`}>
        <div className="max-w-4xl mx-auto px-4 sm:px-8">
          <div className="flex flex-col sm:flex-row gap-8 pt-12"> {/* Reduced gap from gap-16 to gap-8 */}
            {/* Left Sidebar */}
            <aside className="sm:w-24 shrink-0"> {/* Reduced width from w-64 to w-48 */}
              <div className="flex sm:flex-col justify-between sm:space-y-4 sm:sticky sm:top-12">
              <div className="flex items-center sm:block">
                <Link href="/">
                  <img
                    src="images/fe/my_pi_2.png"
                    alt="Karthik Yeluripati"
                    className="w-20 h-20 rounded-full object-cover  transform hover:rotate-12 transition-all duration-300 "
                  />
                </Link>
              </div>
  
                {/* Navigation - tighter spacing */}
                <div>
                <nav className={`flex sm:flex-col sm:space-y-1 sm:text-right text-sm sm:text-base`}> {/* Reduced space-y-2 to space-y-1 */}
                  <NavLink href="/projects" className="text-gray-500 hover:text-gray-900">Projects</NavLink>
                  <NavLink href="/publications" className="text-gray-500 hover:text-gray-900">Research</NavLink>
                  {/* <NavLink href="/now" className="text-gray-500 hover:text-gray-900">Now</NavLink> */}
                  <NavLink href="/contact" className="text-gray-500 hover:text-gray-900">Contact</NavLink>
                </nav>
                </div>
              </div>
            </aside>
  
            {/* Main Content */}
            <main className="flex-1 min-h-screen">
              <div className="max-w-2xl">
                {children}
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
